//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESA_Res_v0
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTable
    {
        public CompanyTable()
        {
            this.CustomerTable = new HashSet<CustomerTable>();
        }
    
        public int companyID { get; set; }
        public string companyName { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string phoneNumber { get; set; }
        public string fax { get; set; }
        public string mail { get; set; }
        public string taxAdmin { get; set; }
        public string taxNum { get; set; }
        public Nullable<int> discountPer { get; set; }
    
        public virtual ICollection<CustomerTable> CustomerTable { get; set; }
    }
}
