//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESA_Res_v0
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientsTable
    {
        public int IngId { get; set; }
        public string IngName { get; set; }
        public double IngQuantity { get; set; }
        public string IngUnit { get; set; }
    }
}
