//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESA_Res_v0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tesaresdbEntities : DbContext
    {
        public tesaresdbEntities()
            : base("name=tesaresdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AuthorizationTable> AuthorizationTable { get; set; }
        public DbSet<CategoryTable> CategoryTable { get; set; }
        public DbSet<FreqUsedTable> FreqUsedTable { get; set; }
        public DbSet<OrderTable> OrderTable { get; set; }
        public DbSet<PaymentTable> PaymentTable { get; set; }
        public DbSet<PaymentTypeTable> PaymentTypeTable { get; set; }
        public DbSet<ProductTable> ProductTable { get; set; }
        public DbSet<StateTable> StateTable { get; set; }
        public DbSet<TableTable> TableTable { get; set; }
        public DbSet<TransactionTable> TransactionTable { get; set; }
        public DbSet<UserTable> UserTable { get; set; }
        public DbSet<IngredientsTable> IngredientsTable { get; set; }
        public DbSet<RecipeTable> RecipeTable { get; set; }
    }
}
