//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESA_Res_v0
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int OrderId { get; set; }
        public int TableId { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
        public double Number { get; set; }
        public double Cost { get; set; }
        public System.DateTime Time { get; set; }
        public bool Dlt { get; set; }
    }
}
