//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESA_Res_v0
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTable
    {
        public int PaymentId { get; set; }
        public string OrderIds { get; set; }
        public double TotalCost { get; set; }
        public System.DateTime Time { get; set; }
        public int TableId { get; set; }
    }
}
