//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESA_Res_v0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Product
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public int productCat { get; set; }
        public byte[] productImage { get; set; }
        public Nullable<int> productPrice { get; set; }
        public Nullable<int> productPrepTime { get; set; }
        public string productPrepPlace { get; set; }
    
        public virtual Product_Categories_Table Product_Categories_Table { get; set; }
        public virtual Product_Categories_Table Product_Categories_Table1 { get; set; }
    }
}
