//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESA_Res_v0
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeTable
    {
        public int RecId { get; set; }
        public string RecName { get; set; }
        public string RecIngredients { get; set; }
    }
}
