//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESA_Res_v0.oldsss
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizationTable
    {
        public int AuthId { get; set; }
        public int UserId { get; set; }
        public string AuthP { get; set; }
    }
}
