//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESA_Res_v0.oldsss
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TesaResDB_Entities : DbContext
    {
        public TesaResDB_Entities()
            : base("name=TesaResDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AuthorizationTable> AuthorizationTables { get; set; }
        public DbSet<CategoryTable> CategoryTables { get; set; }
        public DbSet<FreqUsedTable> FreqUsedTables { get; set; }
        public DbSet<OrderTable> OrderTables { get; set; }
        public DbSet<PaymentTable> PaymentTables { get; set; }
        public DbSet<PaymentTypeTable> PaymentTypeTables { get; set; }
        public DbSet<ProductTable> ProductTables { get; set; }
        public DbSet<TableTable> TableTables { get; set; }
        public DbSet<TransactionTable> TransactionTables { get; set; }
        public DbSet<UserTable> UserTables { get; set; }
        public DbSet<StateTable> StateTables { get; set; }
    }
}
